# Generated by Django 5.2.15 on 2026-08-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sharedcartitem_itemcomment_squad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomment',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sharedcartitem',
            name='added_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squad',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='squad',
            name='members',
        ),
        migrations.AddField(
            model_name='squad',
            name='members',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
