# Generated by Django 5.2.15 on 2026-08-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_itemcomment_user_alter_sharedcartitem_added_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessionCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='default_user', max_length=100, unique=True)),
                ('cart_data', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
